# Generated by Django 4.2.9 on 2024-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photomanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='biography',
            field=models.TextField(max_length=1000, verbose_name='About Me'),
        ),
    ]
