# Generated by Django 4.2.9 on 2024-05-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photomanager', '0002_alter_photographer_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photomanager.photographer'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('e', 'Event'), ('w', 'Wedding'), ('o', 'Outdoor'), ('h', 'Headshot'), ('p', 'Product'), ('a', 'Art')], max_length=6),
        ),
    ]
